version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: cashDB
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306

volumes:
  db_data: {}